---
layout: lesson
title: Assignment 10
subtitle: "EDH7916 | Summer C 2020"
author: Benjamin Skinner
order: 10
category: problemset
links:
  pdf: assignment_10.pdf
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---

I have been opinionated throughout this course (and in lesson 10 in
particular) about the best ways to organize a quantitative data
workflow. Considering all of that, please answer the following two
questions in a Markdown (`*.md`) file, giving about half of a page to
each answer:

1. What organizational/work flow practice do you think is unnecessary
   or impractical for daily data analytic tasks? Why? (Keep in mind that
   practice doesn't have to include using R, but could instead mean
   using SPSS, Excel, _etc_.)
1. What organizational/work flow practice have I _not_ included that
   you think would help reduce error or improve reproducibility? Why?

#### Submission details

- Upload your script (`<lastname>_assignment_10.md`) to our CANVAS
  course site no later than 11:59 p.m. EDT on the due date.




