---
layout: lesson
title: "Assignment: Data Visualization with ggplot II"
subtitle: EDH7916
author: Benjamin Skinner
order: 6
category: extra
links:
  pdf: assignment_plotting_ii.pdf
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---

Using `hsls_small.csv`, please answer the following question. Use
comments to respond as necessary.

## Question

1. Make 3-4 different figures showing relationships between variables
in `hsls_small`. You can remake some figures we made in prior lesson,
but whatever you do, make sure that data are clean, everything is
properly labeled, tick marks are appropriately spaced and numbered ---
just that the figures look nice. Once done, put them together in a
nice arrangement using patchwork. This may mean making some
adjustments so that there's no redundant information in the final
figure.

#### Submission details

- Save your script (`<lastname>_assignment_plotting_ii.R`) in your `scripts`
  directory.
- Push changes to your repo (the new script and new folder) to GitHub
  prior to the next class session.





