---
layout: lesson
title: Supplemental Assignment 4
subtitle: "EDH7916 | Summer C 2020"
author: Benjamin Skinner
order: 4
category: supplemental
links:
  pdf: supplemental_assignment_4.pdf
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---

Using the plotly library (no conversions from ggplot), make **3**
interactive figures using data from your final project. The figures
should be well labeled with a nice tooltip.

For each figure, show your data work and give 2-3 sentences explaning
how the interactive figure improves upon a static figure or allows you
to show a relation that you couldn't show with a static figure.

You **do not** need to save the final output as a data or figure file:
just having the final result print to the console is fine. 

**NOTE** I should have your final project data, but it is fine if you
want to include a subset. Just make sure that I have your data so that
I can run your code.

#### Submission details

- Upload your script (`<lastname>_supplemental_assignment_4.R`) to our CANVAS
  course site no later than 11:59 p.m. EDT on the due date.

