---
layout: lesson
title: Assignment 6
subtitle: EDH7916
author: Benjamin Skinner
order: 6
category: problemset
links:
  pdf: assignment_6.pdf
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---

For this assignment, I want you to create a 1-2 page RMD document that
uses `hsls_small.dta` to answer the following questions:

> Do educational expectations between a student and their parents
> generally differ?  If so, which group tends to have higher
> expectations? Do differences vary by the parents' own educational
> attainment?

Your final file should include at least one figure and at least one
table of summary statistics. The figure and table should be formatted
nicely, with good axis labels and column names. You should explain
your findings in the document text using Markdown syntax. You do not
need to use or cite outside sources --- just describe what you
find. You also do not need to perform inferential tests (_e.g._ t-test
of differences), though you can if you wish. I should not see input
code in the final document --- only the final clean output. In other
words, it should look like a product you would give to a boss or would
want given to you.

I recommend using `test_score.Rmd` as a template for how you should:

1. Read in the data
2. Wrangle the data as necessary to generate your analysis
3. Create any tables you may have
4. Create any figures you may have

Feel free to repurpose any code you've seen in prior lessons, but make
sure you answer the question to the best of your ability.

#### Submission details

- Save both your code file (`<lastname>_assignment_6.Rmd`) and
  compiled document (`<lastname>_assignment_6.pdf`) in your scripts
  directory.
- Push changes to your repo (the new script and new folder) to GitHub
  prior to the next class session.
