---
layout: lesson
title: Assignment 5
subtitle: "EDH7916 | Spring 2020"
author: Benjamin Skinner
order: 6
category: assignment
links:
  pdf: dw_three_hw.pdf
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---

_**NOTE** This assignment needs to be completed by the start of the
next class. That means everything pushed to your remote GitHub repo
before class starts._

_Remember, I encourage you to save your work, commit smaller changes,
and push to your remote GitHub repo often rather than wait until the
last minute._

Use the two IPEDS data sets we used in class, `hd2007.csv` and
`ic2007mission.csv` as well as `ufl_class_times.csv` to answer the
following questions. You will need to join them. You may also need to
look up the data dictionaries for each file. Click the "continue"
button on [this
page](https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx) to see the
data and accompanying dictionary files.

You **do not** need to save the final output as a data file: just
having the final result print to the console is fine. For each
question, I would like you to try to pipe all the commands
together. Throughout, you **should** account for missing values to the
best of your ability by dropping them.

For each question, show your data work and then answer the question in
a short (1-2 sentence(s)) comment. 

## Questions

1. How many chief administrator names start with "Dr."? **NB** Many
   chief administrators are listed on more than one line due to branch
   campuses. Make sure to take this into account by keeping only
   distinct names.
1. Among those schools that give their mission statement:
   1. How many repeat their institutional name in their mission
   statement?  
   1. How many use the word _civic_?
   1. Which top 3 states have the most schools with mission statements
      that use the word _future_?  
   1. Which type of schools (public, private-non-profit,
      private-for-profit) are most likely to use the word _skill_ in
      their mission statement?
1. Among the schools that closed in 2007 or 2008 and give a date with
   a day, month and year:
   1. Which has been closed for the longest time? How many months has
      it been from its close date to the beginning of this current
      month (1 February 2020)?  
   1. How many days were there between the first school to close and
      the last?
	  
**BONUS**
1. Using the `ufl_class_times.csv` data set, answer the following
   question: _how many minutes of study time should a student have
   available during a typical 7 day week with the following schedule_?
   - MWF class: period 2
   - MW class: period 5 - 6
   - TR class: period 7 - 8
   - R class: period 10 - E1
   
   Assumptions: 
   1. The student takes 30 minutes to travel between home and school.  
   1. The student arrives on campus from just in time for the first
      class and leaves just after the last class.  
   1. The student sleeps 7 hours a night.  
   1. The student works 15 hours a week, with a 10 minute commute.  
  






