---
layout: lesson
title: Proposal
subtitle: "EDH7916"
author: Benjamin Skinner
order: 1
category: finalproject
links:
  pdf: fp_proposal.pdf
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---

From the syllabus:

> For your final project, you must produce a 3-5 page report on a higher
> education topic of interest. The report should be a combination of
> writing, tables, and figures, have minimal citations (if any), and be
> fully reproducible with minimal effort. You must use data that is
> either publicly available or that can be shared with others (no IRB
> restrictions). Everyone will submit three preliminary assignments in
> addition to the final report. 

**This assignment represents the first of those three preliminary
assignments.**

For your final project proposal, I need the following in a cleanly
formatted Markdown (`.md`) file:

1. A paragraph describing your project: 
   - What will you be predicting?
   - Why is it interesting?
1. A description of where you will find this data.
1. A few lines describing your dependent variable in detail. What is
   the nature of this outcome as a variable?

#### Submission details

- Save your file as `<name>_proposal.md` where your last name
  replaces `<name>` (_e.g._ `skinner_proposal.md`) in your
  `final_project` folder
- Push to your GitHub repo prior to the start of the class in which it
  is due. If you are unsure whether you have successfully pushed your
  changes, check the online version of your repo at GitHub.com. If you
  can see your changes there, I can see them too.
