---
layout: lesson
title: Introduction Problem Set
subtitle: "EDH7916 | Spring 2020"
author: Benjamin Skinner
order: 1
category: assignment
links:
  pdf: introduction_ps.pdf
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---

_**NOTE** This assignment needs to be completed by the Sunday evening
before the second class. This will give us time to meet before the
second class session if you are having trouble getting started._

1. If you don't complete all the setup during class time, do the following:
    1. Download and install all required software.
    2. Register for GitHub and submit an request for an education
    discount.
    3. Clone your repo (`student_<your_last_name>`) to your machine
    --- I recommend saving inside another directory where you store
    class files, _e.g._,
    `~/courses/edh7916/student_<your_last_name>`.
1. Initialize a script called `introduction_ps_<your_last_name>.r` in your
   `/scripts` directory.
1. Read through the supplemental material on [**Data types and
   structures**](https://edquant.github.io/edh7916/lessons/types_structures.html)
   and answer the "Quick exercises" in your script.
1. At the bottom, add a commented note on what you hope to get out of
   this course and any concerns you may have.
1. Making sure you've saved your file, take the following steps to
   add, commit, and push your work:
   1. `git add` your changes to your repo.
   2. `git commit` your changes with a short but informative message.
   3. `git push` your commit to GitHub.
   4. Log into the GitHub website, navigate to your repo, and
      confirm that you can see your changes.
