---
layout: lesson
title: Supplemental Assignment 1
subtitle: "EDH7916 | Summer C 2020"
author: Benjamin Skinner
order: 1
category: supplemental
links:
  pdf: supplemental_assignment_1.pdf
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---

Choose one of the **Other** data sources shown at the bottom of the
the [first supplemental lesson on getting higher education data from
common sources](/edh7916/lessons/getting_data.html) and create a
Markdown document that does two things:

1. Explains the source and its usefulness for higher education
   research (one paragraph)
1. Gives step-by-step directions with links and screenshots on how to
   find and download the data
   
**NOTE:** A couple of the **Other** sources are general links to
organizations with a number of data sources (_e.g._ the Bureau of
Labor Statistics). Choose **one** data source if there are more than
one.

A good document will include:

1. Clear instructions for finding and downloading the data without
   missing steps
1. Properly formatted links that work
1. Screenshots that either
   1. Include boxes, arrows, and text to help the eye
   1. Include _very_ detailed captions/notes that explain where to
      look, what to click, _etc_
1. A clear connection to higher education research
  
#### Submission details

- Upload your script (`<lastname>_supplemental_assignment_1.md`) and
  the compiled document (same file name: either `.html` or `.pdf`) to
  our CANVAS course site no later than 11:59 p.m. EDT on the due date.
